# Generated by Django 3.2.3 on 2021-05-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='rent_price',
            field=models.FloatField(default=0),
        ),
    ]
